In [1]:
from pathlib import Path

import pandas as pd

In [15]:
DATA_DIR = Path("../data/raw")

for file in DATA_DIR.iterdir():
    print(file.name)

GSE226105_rLog-Normalized_counts.csv

In [16]:
DATA_PATH = Path("../data/raw/GSE226105_rLog-Normalized_counts.csv")

df = pd.read_csv(DATA_PATH)

In [17]:
df.shape

(28775, 58)

In [18]:
df.head()

,Unnamed: 0,endpoint_COLD HL 1,endpoint_COLD HL 2,endpoint_COLD HL 3,endpoint_COLD 1,endpoint_COLD 2,endpoint_COLD 3,endpoint_T1,endpoint_T 2,endpoint_T 3,...,recovery_DROUGHT 3,recovery_Humidity 1,recovery_Humidity 2,recovery_Humidity 3,recovery_HL 1,recovery_HL 2,recovery_HL 3,CONT 1,CONT 2,CONT 3
0,AT1G01010,6.301350,6.404737,5.914146,5.993385,5.960478,5.694622,6.297380,5.958532,6.198098,...,5.810787,5.845085,5.674878,5.667744,5.766560,6.168910,5.990605,5.671686,5.713255,5.871097
1,AT1G01020,8.071226,8.268410,8.146478,8.010670,8.054365,7.965823,8.142792,7.699210,8.185703,...,7.853829,7.788381,7.590621,7.648822,7.887382,7.804466,7.860458,7.698647,7.515656,7.705563
2,AT1G01030,6.224397,5.792192,5.742243,6.053377,5.857522,5.628435,5.977911,5.795870,5.917823,...,5.787485,5.891773,5.858537,5.842798,5.633534,5.883066,5.903216,5.740828,5.759991,5.624435
3,AT1G01040,10.430289,10.387012,10.388520,10.162534,10.260200,10.028171,10.131184,9.945119,10.411739,...,10.041923,9.774146,9.889913,9.989144,9.952409,10.178882,10.104253,10.045914,9.804080,9.809133
4,AT1G01046,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28775 entries, 0 to 28774
Data columns (total 58 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               28775 non-null  object
 1   endpoint_COLD HL 1       28775 non-null  float64
 2   endpoint_COLD HL 2       28775 non-null  float64
 3   endpoint_COLD HL 3       28775 non-null  float64
 4   endpoint_COLD 1          28775 non-null  float64
 5   endpoint_COLD 2          28775 non-null  float64
 6   endpoint_COLD 3          28775 non-null  float64
 7   endpoint_T1              28775 non-null  float64
 8   endpoint_T 2             28775 non-null  float64
 9   endpoint_T 3             28775 non-null  float64
 10  endpoint_HEAT HL 1       28775 non-null  float64
 11  endpoint_HEAT HL 2       28775 non-null  float64
 12  endpoint_HEAT HL 3       28775 non-null  float64
 13  endpoint_HEAT DROUGHT 1  28775 non-null  float64
 14  endpoint_HEAT DROUGHT 2  28775 non-null  float64
 15  endpoint_HEAT DROUGHT 3  28775 non-null  float64
 16  endpoint_HEAT 1          28775 non-null  float64
 17  endpoint_HEAT 2          28775 non-null  float64
 18  endpoint_HEAT 3          28775 non-null  float64
 19  endpoint_DROUGHT 1       28775 non-null  float64
 20  endpoint_DROUGHT 2       28775 non-null  float64
 21  endpoint_DROUGHT 3       28775 non-null  float64
 22  endpoint_Humidity 1      28775 non-null  float64
 23  endpoint_Humidity 2      28775 non-null  float64
 24  endpoint_Humidity 3      28775 non-null  float64
 25  endpoint_HL 1            28775 non-null  float64
 26  endpoint_HL 2            28775 non-null  float64
 27  endpoint_HL 3            28775 non-null  float64
 28  recovery_COLD HL 1       28775 non-null  float64
 29  recovery_COLD HL 2       28775 non-null  float64
 30  recovery_COLD HL 3       28775 non-null  float64
 31  recovery_COLD 1          28775 non-null  float64
 32  recovery_COLD 2          28775 non-null  float64
 33  recovery_COLD 3          28775 non-null  float64
 34  recovery_T1              28775 non-null  float64
 35  recovery_T 2             28775 non-null  float64
 36  recovery_T 3             28775 non-null  float64
 37  recovery_HEAT HL 1       28775 non-null  float64
 38  recovery_HEAT HL 2       28775 non-null  float64
 39  recovery_HEAT HL 3       28775 non-null  float64
 40  recovery_HEAT DROUGHT 1  28775 non-null  float64
 41  recovery_HEAT DROUGHT 2  28775 non-null  float64
 42  recovery_HEAT DROUGHT 3  28775 non-null  float64
 43  recovery_HEAT 1          28775 non-null  float64
 44  recovery_HEAT 2          28775 non-null  float64
 45  recovery_HEAT 3          28775 non-null  float64
 46  recovery_DROUGHT 1       28775 non-null  float64
 47  recovery_DROUGHT 2       28775 non-null  float64
 48  recovery_DROUGHT 3       28775 non-null  float64
 49  recovery_Humidity 1      28775 non-null  float64
 50  recovery_Humidity 2      28775 non-null  float64
 51  recovery_Humidity 3      28775 non-null  float64
 52  recovery_HL 1            28775 non-null  float64
 53  recovery_HL 2            28775 non-null  float64
 54  recovery_HL 3            28775 non-null  float64
 55  CONT 1                   28775 non-null  float64
 56  CONT 2                   28775 non-null  float64
 57  CONT 3                   28775 non-null  float64
dtypes: float64(57), object(1)
memory usage: 12.7+ MB

In [20]:
df.columns

Index(['Unnamed: 0', 'endpoint_COLD HL 1', 'endpoint_COLD HL 2',
       'endpoint_COLD HL 3', 'endpoint_COLD 1', 'endpoint_COLD 2',
       'endpoint_COLD 3', 'endpoint_T1', 'endpoint_T 2', 'endpoint_T 3',
       'endpoint_HEAT HL 1', 'endpoint_HEAT HL 2', 'endpoint_HEAT HL 3',
       'endpoint_HEAT DROUGHT 1', 'endpoint_HEAT DROUGHT 2',
       'endpoint_HEAT DROUGHT 3', 'endpoint_HEAT 1', 'endpoint_HEAT 2',
       'endpoint_HEAT 3', 'endpoint_DROUGHT 1', 'endpoint_DROUGHT 2',
       'endpoint_DROUGHT 3', 'endpoint_Humidity 1', 'endpoint_Humidity 2',
       'endpoint_Humidity 3', 'endpoint_HL 1', 'endpoint_HL 2',
       'endpoint_HL 3', 'recovery_COLD HL 1', 'recovery_COLD HL 2',
       'recovery_COLD HL 3', 'recovery_COLD 1', 'recovery_COLD 2',
       'recovery_COLD 3', 'recovery_T1', 'recovery_T 2', 'recovery_T 3',
       'recovery_HEAT HL 1', 'recovery_HEAT HL 2', 'recovery_HEAT HL 3',
       'recovery_HEAT DROUGHT 1', 'recovery_HEAT DROUGHT 2',
       'recovery_HEAT DROUGHT 3', 'recovery_HEAT 1', 'recovery_HEAT 2',
       'recovery_HEAT 3', 'recovery_DROUGHT 1', 'recovery_DROUGHT 2',
       'recovery_DROUGHT 3', 'recovery_Humidity 1', 'recovery_Humidity 2',
       'recovery_Humidity 3', 'recovery_HL 1', 'recovery_HL 2',
       'recovery_HL 3', 'CONT 1', 'CONT 2', 'CONT 3'],
      dtype='object')

In [25]:
df["Unnamed: 0"].nunique()

28775

In [27]:
print(df.columns[0])
print(df.iloc[:10, 0].tolist())
print(df.iloc[:, 0].nunique())

Unnamed: 0
['AT1G01010', 'AT1G01020', 'AT1G01030', 'AT1G01040', 'AT1G01046', 'AT1G01050', 'AT1G01060', 'AT1G01070', 'AT1G01073', 'AT1G01080']
28775

In [28]:
df["Unnamed: 0"].duplicated().sum()

np.int64(0)

In [29]:
df["Unnamed: 0"].str.startswith("AT").value_counts()

Unnamed: 0
True    28775
Name: count, dtype: int64

In [36]:
df = df.rename(columns={"Unnamed: 0" : "gene_id" })

print(df.columns[:5].tolist())

['gene_id', 'endpoint_COLD HL 1', 'endpoint_COLD HL 2', 'endpoint_COLD HL 3', 'endpoint_COLD 1']

In [34]:
sample_columns = df.columns[1:]

for column in sample_columns:

 print(column)

endpoint_COLD HL 1
endpoint_COLD HL 2
endpoint_COLD HL 3
endpoint_COLD 1
endpoint_COLD 2
endpoint_COLD 3
endpoint_T1
endpoint_T 2
endpoint_T 3
endpoint_HEAT HL 1
endpoint_HEAT HL 2
endpoint_HEAT HL 3
endpoint_HEAT DROUGHT 1
endpoint_HEAT DROUGHT 2
endpoint_HEAT DROUGHT 3
endpoint_HEAT 1
endpoint_HEAT 2
endpoint_HEAT 3
endpoint_DROUGHT 1
endpoint_DROUGHT 2
endpoint_DROUGHT 3
endpoint_Humidity 1
endpoint_Humidity 2
endpoint_Humidity 3
endpoint_HL 1
endpoint_HL 2
endpoint_HL 3
recovery_COLD HL 1
recovery_COLD HL 2
recovery_COLD HL 3
recovery_COLD 1
recovery_COLD 2
recovery_COLD 3
recovery_T1
recovery_T 2
recovery_T 3
recovery_HEAT HL 1
recovery_HEAT HL 2
recovery_HEAT HL 3
recovery_HEAT DROUGHT 1
recovery_HEAT DROUGHT 2
recovery_HEAT DROUGHT 3
recovery_HEAT 1
recovery_HEAT 2
recovery_HEAT 3
recovery_DROUGHT 1
recovery_DROUGHT 2
recovery_DROUGHT 3
recovery_Humidity 1
recovery_Humidity 2
recovery_Humidity 3
recovery_HL 1
recovery_HL 2
recovery_HL 3
CONT 1
CONT 2
CONT 3

In [35]:
condition_map = {
    "COLD HL": "cold_high_light",
    "COLD": "cold",
    "T": "heat_drought_high_light",
    "HEAT HL": "heat_high_light",
    "HEAT DROUGHT": "heat_drought",
    "HEAT": "heat",
    "DROUGHT": "drought",
    "Humidity": "high_humidity",
    "HL": "high_light",
}

In [41]:
import re

records = []

for column in sample_columns:

    if column.startswith("CONT"):
        state = "control"
        condition = "control"
        replicate = int(re.search(r"\d+$", column).group())

    else:
        state, remainder = column.split("_", 1)

        replicate = int(re.search(r"\d+$", remainder).group())

        source_condition = re.sub(r"\s*\d+$", "", remainder).strip()

        condition = condition_map[source_condition]

    records.append({
        "matrix_column": column,
        "state": state,
        "condition": condition,
        "replicate": replicate,
    })

sample_manifest = pd.DataFrame(records)

sample_manifest

              matrix_column     state                condition  replicate
0        endpoint_COLD HL 1  endpoint          cold_high_light          1
1        endpoint_COLD HL 2  endpoint          cold_high_light          2
2        endpoint_COLD HL 3  endpoint          cold_high_light          3
3           endpoint_COLD 1  endpoint                     cold          1
4           endpoint_COLD 2  endpoint                     cold          2
5           endpoint_COLD 3  endpoint                     cold          3
6               endpoint_T1  endpoint  heat_drought_high_light          1
7              endpoint_T 2  endpoint  heat_drought_high_light          2
8              endpoint_T 3  endpoint  heat_drought_high_light          3
9        endpoint_HEAT HL 1  endpoint          heat_high_light          1
10       endpoint_HEAT HL 2  endpoint          heat_high_light          2
11       endpoint_HEAT HL 3  endpoint          heat_high_light          3
12  endpoint_HEAT DROUGHT 1  endpoint             heat_drought          1
13  endpoint_HEAT DROUGHT 2  endpoint             heat_drought          2
14  endpoint_HEAT DROUGHT 3  endpoint             heat_drought          3
15          endpoint_HEAT 1  endpoint                     heat          1
16          endpoint_HEAT 2  endpoint                     heat          2
17          endpoint_HEAT 3  endpoint                     heat          3
18       endpoint_DROUGHT 1  endpoint                  drought          1
19       endpoint_DROUGHT 2  endpoint                  drought          2
20       endpoint_DROUGHT 3  endpoint                  drought          3
21      endpoint_Humidity 1  endpoint            high_humidity          1
22      endpoint_Humidity 2  endpoint            high_humidity          2
23      endpoint_Humidity 3  endpoint            high_humidity          3
24            endpoint_HL 1  endpoint               high_light          1
25            endpoint_HL 2  endpoint               high_light          2
26            endpoint_HL 3  endpoint               high_light          3
27       recovery_COLD HL 1  recovery          cold_high_light          1
28       recovery_COLD HL 2  recovery          cold_high_light          2
29       recovery_COLD HL 3  recovery          cold_high_light          3
30          recovery_COLD 1  recovery                     cold          1
31          recovery_COLD 2  recovery                     cold          2
32          recovery_COLD 3  recovery                     cold          3
33              recovery_T1  recovery  heat_drought_high_light          1
34             recovery_T 2  recovery  heat_drought_high_light          2
35             recovery_T 3  recovery  heat_drought_high_light          3
36       recovery_HEAT HL 1  recovery          heat_high_light          1
37       recovery_HEAT HL 2  recovery          heat_high_light          2
38       recovery_HEAT HL 3  recovery          heat_high_light          3
39  recovery_HEAT DROUGHT 1  recovery             heat_drought          1
40  recovery_HEAT DROUGHT 2  recovery             heat_drought          2
41  recovery_HEAT DROUGHT 3  recovery             heat_drought          3
42          recovery_HEAT 1  recovery                     heat          1
43          recovery_HEAT 2  recovery                     heat          2
44          recovery_HEAT 3  recovery                     heat          3
45       recovery_DROUGHT 1  recovery                  drought          1
46       recovery_DROUGHT 2  recovery                  drought          2
47       recovery_DROUGHT 3  recovery                  drought          3
48      recovery_Humidity 1  recovery            high_humidity          1
49      recovery_Humidity 2  recovery            high_humidity          2
50      recovery_Humidity 3  recovery            high_humidity          3
51            recovery_HL 1  recovery               high_light          1
52            recovery_HL 2  recovery               high_light          2
53            recovery_HL 3  recovery               high_light          3
54                   CONT 1   control                  control          1
55                   CONT 2   control                  control          2
56                   CONT 3   control                  control          3

In [42]:
sample_manifest.shape

(57, 4)

In [43]:
design_check = (
    sample_manifest
    .groupby(["state", "condition"])
    .agg(
        n_samples=("matrix_column", "size"),
        replicates=("replicate", lambda x: sorted(x.tolist()))
    )
    .reset_index()
)

design_check

       state                condition  n_samples replicates
0    control                  control          3  [1, 2, 3]
1   endpoint                     cold          3  [1, 2, 3]
2   endpoint          cold_high_light          3  [1, 2, 3]
3   endpoint                  drought          3  [1, 2, 3]
4   endpoint                     heat          3  [1, 2, 3]
5   endpoint             heat_drought          3  [1, 2, 3]
6   endpoint  heat_drought_high_light          3  [1, 2, 3]
7   endpoint          heat_high_light          3  [1, 2, 3]
8   endpoint            high_humidity          3  [1, 2, 3]
9   endpoint               high_light          3  [1, 2, 3]
10  recovery                     cold          3  [1, 2, 3]
11  recovery          cold_high_light          3  [1, 2, 3]
12  recovery                  drought          3  [1, 2, 3]
13  recovery                     heat          3  [1, 2, 3]
14  recovery             heat_drought          3  [1, 2, 3]
15  recovery  heat_drought_high_light          3  [1, 2, 3]
16  recovery          heat_high_light          3  [1, 2, 3]
17  recovery            high_humidity          3  [1, 2, 3]
18  recovery               high_light          3  [1, 2, 3]

In [44]:
sample_manifest["heat"] = sample_manifest["condition"].isin([
    "heat",
    "heat_drought",
    "heat_high_light",
    "heat_drought_high_light",
])

sample_manifest["drought"] = sample_manifest["condition"].isin([
    "drought",
    "heat_drought",
    "heat_drought_high_light",
])

sample_manifest["high_light"] = sample_manifest["condition"].isin([
    "high_light",
    "cold_high_light",
    "heat_high_light",
    "heat_drought_high_light",
])

sample_manifest["cold"] = sample_manifest["condition"].isin([
    "cold",
    "cold_high_light",
])

sample_manifest["high_humidity"] = (
    sample_manifest["condition"] == "high_humidity"
)

sample_manifest

,matrix_column,state,condition,replicate,heat,drought,high_light,cold,high_humidity
0,endpoint_COLD HL 1,endpoint,cold_high_light,1,False,False,True,True,False
1,endpoint_COLD HL 2,endpoint,cold_high_light,2,False,False,True,True,False
2,endpoint_COLD HL 3,endpoint,cold_high_light,3,False,False,True,True,False
3,endpoint_COLD 1,endpoint,cold,1,False,False,False,True,False
4,endpoint_COLD 2,endpoint,cold,2,False,False,False,True,False
5,endpoint_COLD 3,endpoint,cold,3,False,False,False,True,False
6,endpoint_T1,endpoint,heat_drought_high_light,1,True,True,True,False,False
7,endpoint_T 2,endpoint,heat_drought_high_light,2,True,True,True,False,False
8,endpoint_T 3,endpoint,heat_drought_high_light,3,True,True,True,False,False
9,endpoint_HEAT HL 1,endpoint,heat_high_light,1,True,False,True,False,False
10,endpoint_HEAT HL 2,endpoint,heat_high_light,2,True,False,True,False,False
11,endpoint_HEAT HL 3,endpoint,heat_high_light,3,True,False,True,False,False
12,endpoint_HEAT DROUGHT 1,endpoint,heat_drought,1,True,True,False,False,False
13,endpoint_HEAT DROUGHT 2,endpoint,heat_drought,2,True,True,False,False,False
14,endpoint_HEAT DROUGHT 3,endpoint,heat_drought,3,True,True,False,False,False
15,endpoint_HEAT 1,endpoint,heat,1,True,False,False,False,False
16,endpoint_HEAT 2,endpoint,heat,2,True,False,False,False,False
17,endpoint_HEAT 3,endpoint,heat,3,True,False,False,False,False
18,endpoint_DROUGHT 1,endpoint,drought,1,False,True,False,False,False
19,endpoint_DROUGHT 2,endpoint,drought,2,False,True,False,False,False
20,endpoint_DROUGHT 3,endpoint,drought,3,False,True,False,False,False
21,endpoint_Humidity 1,endpoint,high_humidity,1,False,False,False,False,True
22,endpoint_Humidity 2,endpoint,high_humidity,2,False,False,False,False,True
23,endpoint_Humidity 3,endpoint,high_humidity,3,False,False,False,False,True
24,endpoint_HL 1,endpoint,high_light,1,False,False,True,False,False
25,endpoint_HL 2,endpoint,high_light,2,False,False,True,False,False
26,endpoint_HL 3,endpoint,high_light,3,False,False,True,False,False
27,recovery_COLD HL 1,recovery,cold_high_light,1,False,False,True,True,False
28,recovery_COLD HL 2,recovery,cold_high_light,2,False,False,True,True,False
29,recovery_COLD HL 3,recovery,cold_high_light,3,False,False,True,True,False
30,recovery_COLD 1,recovery,cold,1,False,False,False,True,False
31,recovery_COLD 2,recovery,cold,2,False,False,False,True,False
32,recovery_COLD 3,recovery,cold,3,False,False,False,True,False
33,recovery_T1,recovery,heat_drought_high_light,1,True,True,True,False,False
34,recovery_T 2,recovery,heat_drought_high_light,2,True,True,True,False,False
35,recovery_T 3,recovery,heat_drought_high_light,3,True,True,True,False,False
36,recovery_HEAT HL 1,recovery,heat_high_light,1,True,False,True,False,False
37,recovery_HEAT HL 2,recovery,heat_high_light,2,True,False,True,False,False
38,recovery_HEAT HL 3,recovery,heat_high_light,3,True,False,True,False,False
39,recovery_HEAT DROUGHT 1,recovery,heat_drought,1,True,True,False,False,False
40,recovery_HEAT DROUGHT 2,recovery,heat_drought,2,True,True,False,False,False
41,recovery_HEAT DROUGHT 3,recovery,heat_drought,3,True,True,False,False,False
42,recovery_HEAT 1,recovery,heat,1,True,False,False,False,False
43,recovery_HEAT 2,recovery,heat,2,True,False,False,False,False
44,recovery_HEAT 3,recovery,heat,3,True,False,False,False,False
45,recovery_DROUGHT 1,recovery,drought,1,False,True,False,False,False
46,recovery_DROUGHT 2,recovery,drought,2,False,True,False,False,False
47,recovery_DROUGHT 3,recovery,drought,3,False,True,False,False,False
48,recovery_Humidity 1,recovery,high_humidity,1,False,False,False,False,True
49,recovery_Humidity 2,recovery,high_humidity,2,False,False,False,False,True
50,recovery_Humidity 3,recovery,high_humidity,3,False,False,False,False,True
51,recovery_HL 1,recovery,high_light,1,False,False,True,False,False
52,recovery_HL 2,recovery,high_light,2,False,False,True,False,False
53,recovery_HL 3,recovery,high_light,3,False,False,True,False,False
54,CONT 1,control,control,1,False,False,False,False,False
55,CONT 2,control,control,2,False,False,False,False,False
56,CONT 3,control,control,3,False,False,False,False,False

In [49]:
factor_columns = [
    "heat",
    "drought",
    "high_light",
    "cold",
    "high_humidity",
]

condition_design = (
    sample_manifest[
        ["condition"] + factor_columns
    ]
    .drop_duplicates()
    .sort_values("condition")
    .reset_index(drop=True)
)

condition_design

                 condition   heat  drought  high_light   cold  high_humidity
0                     cold  False    False       False   True          False
1          cold_high_light  False    False        True   True          False
2                  control  False    False       False  False          False
3                  drought  False     True       False  False          False
4                     heat   True    False       False  False          False
5             heat_drought   True     True       False  False          False
6  heat_drought_high_light   True     True        True  False          False
7          heat_high_light   True    False        True  False          False
8            high_humidity  False    False       False  False           True
9               high_light  False    False        True  False          False

In [47]:
sample_manifest["n_stressors"] = (
    sample_manifest[factor_columns]
    .sum(axis=1)
)

sample_manifest

,matrix_column,state,condition,replicate,heat,drought,high_light,cold,high_humidity,n_stressors
0,endpoint_COLD HL 1,endpoint,cold_high_light,1,False,False,True,True,False,2
1,endpoint_COLD HL 2,endpoint,cold_high_light,2,False,False,True,True,False,2
2,endpoint_COLD HL 3,endpoint,cold_high_light,3,False,False,True,True,False,2
3,endpoint_COLD 1,endpoint,cold,1,False,False,False,True,False,1
4,endpoint_COLD 2,endpoint,cold,2,False,False,False,True,False,1
5,endpoint_COLD 3,endpoint,cold,3,False,False,False,True,False,1
6,endpoint_T1,endpoint,heat_drought_high_light,1,True,True,True,False,False,3
7,endpoint_T 2,endpoint,heat_drought_high_light,2,True,True,True,False,False,3
8,endpoint_T 3,endpoint,heat_drought_high_light,3,True,True,True,False,False,3
9,endpoint_HEAT HL 1,endpoint,heat_high_light,1,True,False,True,False,False,2
10,endpoint_HEAT HL 2,endpoint,heat_high_light,2,True,False,True,False,False,2
11,endpoint_HEAT HL 3,endpoint,heat_high_light,3,True,False,True,False,False,2
12,endpoint_HEAT DROUGHT 1,endpoint,heat_drought,1,True,True,False,False,False,2
13,endpoint_HEAT DROUGHT 2,endpoint,heat_drought,2,True,True,False,False,False,2
14,endpoint_HEAT DROUGHT 3,endpoint,heat_drought,3,True,True,False,False,False,2
15,endpoint_HEAT 1,endpoint,heat,1,True,False,False,False,False,1
16,endpoint_HEAT 2,endpoint,heat,2,True,False,False,False,False,1
17,endpoint_HEAT 3,endpoint,heat,3,True,False,False,False,False,1
18,endpoint_DROUGHT 1,endpoint,drought,1,False,True,False,False,False,1
19,endpoint_DROUGHT 2,endpoint,drought,2,False,True,False,False,False,1
20,endpoint_DROUGHT 3,endpoint,drought,3,False,True,False,False,False,1
21,endpoint_Humidity 1,endpoint,high_humidity,1,False,False,False,False,True,1
22,endpoint_Humidity 2,endpoint,high_humidity,2,False,False,False,False,True,1
23,endpoint_Humidity 3,endpoint,high_humidity,3,False,False,False,False,True,1
24,endpoint_HL 1,endpoint,high_light,1,False,False,True,False,False,1
25,endpoint_HL 2,endpoint,high_light,2,False,False,True,False,False,1
26,endpoint_HL 3,endpoint,high_light,3,False,False,True,False,False,1
27,recovery_COLD HL 1,recovery,cold_high_light,1,False,False,True,True,False,2
28,recovery_COLD HL 2,recovery,cold_high_light,2,False,False,True,True,False,2
29,recovery_COLD HL 3,recovery,cold_high_light,3,False,False,True,True,False,2
30,recovery_COLD 1,recovery,cold,1,False,False,False,True,False,1
31,recovery_COLD 2,recovery,cold,2,False,False,False,True,False,1
32,recovery_COLD 3,recovery,cold,3,False,False,False,True,False,1
33,recovery_T1,recovery,heat_drought_high_light,1,True,True,True,False,False,3
34,recovery_T 2,recovery,heat_drought_high_light,2,True,True,True,False,False,3
35,recovery_T 3,recovery,heat_drought_high_light,3,True,True,True,False,False,3
36,recovery_HEAT HL 1,recovery,heat_high_light,1,True,False,True,False,False,2
37,recovery_HEAT HL 2,recovery,heat_high_light,2,True,False,True,False,False,2
38,recovery_HEAT HL 3,recovery,heat_high_light,3,True,False,True,False,False,2
39,recovery_HEAT DROUGHT 1,recovery,heat_drought,1,True,True,False,False,False,2
40,recovery_HEAT DROUGHT 2,recovery,heat_drought,2,True,True,False,False,False,2
41,recovery_HEAT DROUGHT 3,recovery,heat_drought,3,True,True,False,False,False,2
42,recovery_HEAT 1,recovery,heat,1,True,False,False,False,False,1
43,recovery_HEAT 2,recovery,heat,2,True,False,False,False,False,1
44,recovery_HEAT 3,recovery,heat,3,True,False,False,False,False,1
45,recovery_DROUGHT 1,recovery,drought,1,False,True,False,False,False,1
46,recovery_DROUGHT 2,recovery,drought,2,False,True,False,False,False,1
47,recovery_DROUGHT 3,recovery,drought,3,False,True,False,False,False,1
48,recovery_Humidity 1,recovery,high_humidity,1,False,False,False,False,True,1
49,recovery_Humidity 2,recovery,high_humidity,2,False,False,False,False,True,1
50,recovery_Humidity 3,recovery,high_humidity,3,False,False,False,False,True,1
51,recovery_HL 1,recovery,high_light,1,False,False,True,False,False,1
52,recovery_HL 2,recovery,high_light,2,False,False,True,False,False,1
53,recovery_HL 3,recovery,high_light,3,False,False,True,False,False,1
54,CONT 1,control,control,1,False,False,False,False,False,0
55,CONT 2,control,control,2,False,False,False,False,False,0
56,CONT 3,control,control,3,False,False,False,False,False,0

In [48]:
sample_manifest["recovery_days"] = sample_manifest["state"].map({
    "endpoint": 0,
    "recovery": 3,
    "control": 0,
})

In [50]:
sample_manifest["stress_exposed"] = (
    sample_manifest["state"] != "control"
)

In [51]:
sample_manifest[
    ["matrix_column", "state", "condition",
     "n_stressors", "stress_exposed", "recovery_days"]
].head(10)

,matrix_column,state,condition,n_stressors,stress_exposed,recovery_days
0,endpoint_COLD HL 1,endpoint,cold_high_light,2,True,0
1,endpoint_COLD HL 2,endpoint,cold_high_light,2,True,0
2,endpoint_COLD HL 3,endpoint,cold_high_light,2,True,0
3,endpoint_COLD 1,endpoint,cold,1,True,0
4,endpoint_COLD 2,endpoint,cold,1,True,0
5,endpoint_COLD 3,endpoint,cold,1,True,0
6,endpoint_T1,endpoint,heat_drought_high_light,3,True,0
7,endpoint_T 2,endpoint,heat_drought_high_light,3,True,0
8,endpoint_T 3,endpoint,heat_drought_high_light,3,True,0
9,endpoint_HEAT HL 1,endpoint,heat_high_light,2,True,0

One particular nuance that i would like to address. For controls , we are seeing that the recovery_days = 0 , this is merely a convenient numerical encoding; as we learned from the research article that the controls were never recovering from stress. Later, when we formalize the database schema, we may represent this more carefully as “not applicable.”

But for our current exploratory manifest, this representation is sufficient

In [52]:
expression_values = df.drop(columns=["gene_id"])

In [53]:
expression_values.shape

(28775, 57)

In [54]:
expression_values.dtypes.value_counts()

float64    57
Name: count, dtype: int64

In [55]:
expression_values.isna().sum().sum()

np.int64(0)

In [56]:
import numpy as np

np.isinf(expression_values.to_numpy()).sum()

np.int64(0)

In [57]:
expression_values.duplicated().sum()

np.int64(3725)

In [58]:
all_zero_mask = (expression_values == 0).all(axis=1)

all_zero_mask.sum()

np.int64(2657)

In [59]:
constant_mask = expression_values.nunique(axis=1) == 1

constant_mask.sum()

np.int64(2657)

In [60]:
nonzero_expression = expression_values.loc[~all_zero_mask]

nonzero_expression.duplicated().sum()

np.int64(1069)

In [61]:
duplicate_nonzero_mask = (
    ~all_zero_mask
    & expression_values.duplicated(keep=False)
)

duplicate_nonzero_genes = df.loc[
    duplicate_nonzero_mask
]

duplicate_nonzero_genes.head(20)

,gene_id,endpoint_COLD HL 1,endpoint_COLD HL 2,endpoint_COLD HL 3,endpoint_COLD 1,endpoint_COLD 2,endpoint_COLD 3,endpoint_T1,endpoint_T 2,endpoint_T 3,...,recovery_DROUGHT 3,recovery_Humidity 1,recovery_Humidity 2,recovery_Humidity 3,recovery_HL 1,recovery_HL 2,recovery_HL 3,CONT 1,CONT 2,CONT 3
46,AT1G01410,-2.423475,-2.423473,-2.423502,-2.423502,-2.423549,-2.423519,-2.423556,-2.423613,-2.423502,...,-2.423608,-2.423580,-2.423636,-2.423598,-2.423575,-2.423612,-2.423594,-2.423618,-2.423593,-2.423585
55,AT1G01471,-2.423492,-2.423489,-2.423520,-2.423520,-2.423571,-2.423539,-2.423579,-2.423640,-2.423520,...,-2.423635,-2.423604,-2.423665,-2.423624,-2.423599,-2.423639,-2.423619,-2.423645,-2.423618,-2.423610
96,AT1G01870,-2.423469,-2.423467,-2.423495,-2.423495,-2.423541,-2.423512,-2.423548,-2.423604,-2.423495,...,-2.423198,-2.423571,-2.423626,-2.423589,-2.423566,-2.423602,-2.423585,-2.423608,-2.423583,-2.423576
133,AT1G02210,-2.423542,-2.423538,-2.423582,-2.423582,-2.423652,-2.422990,-2.423663,-2.423749,-2.423582,...,-2.423742,-2.423699,-2.423783,-2.423726,-2.423691,-2.423747,-2.423720,-2.423756,-2.423718,-2.423707
153,AT1G02391,-2.423486,-2.423483,-2.423514,-2.423514,-2.423563,-2.423532,-2.423571,-2.423630,-2.423514,...,-2.423625,-2.423596,-2.423654,-2.423615,-2.423590,-2.423629,-2.423610,-2.423635,-2.423609,-2.423601
164,AT1G02480,-2.423556,-2.423551,-2.423606,-2.423606,-2.423693,-2.423638,-2.423707,-2.423813,-2.423606,...,-2.423804,-2.423751,-2.423856,-2.423785,-2.423742,-2.423811,-2.423777,-2.423822,-2.423774,-2.423761
176,AT1G02590,-2.423432,-2.423430,-2.423455,-2.423455,-2.423495,-2.423470,-2.423501,-2.423549,-2.423455,...,-2.423545,-2.423521,-2.423569,-2.423537,-2.423517,-2.423548,-2.423533,-2.423553,-2.423532,-2.423526
193,AT1G02760,-2.372956,-2.372950,-2.373011,-2.373011,-2.373109,-2.373047,-2.373125,-2.373244,-2.373011,...,-2.373233,-2.373175,-2.373292,-2.373212,-2.373164,-2.373241,-2.371485,-2.373254,-2.373200,-2.373185
279,AT1G03515,-2.423487,-2.423484,-2.423515,-2.423515,-2.423564,-2.423533,-2.423572,-2.423632,-2.423515,...,-2.423627,-2.423597,-2.423656,-2.423616,-2.423592,-2.423631,-2.423612,-2.423637,-2.423610,-2.423603
286,AT1G03570,-2.372955,-2.372949,-2.373019,-2.373020,-2.373132,-2.373061,-2.373150,-2.373288,-2.373019,...,-2.373276,-2.373208,-2.373343,-2.373252,-2.373195,-2.373285,-2.373241,-2.373300,-2.373238,-2.373220
300,AT1G03720,-2.423399,-2.423397,-2.423419,-2.423419,-2.423455,-2.423432,-2.423460,-2.423504,-2.423419,...,-2.423500,-2.423479,-2.423521,-2.423492,-2.423475,-2.423503,-2.423489,-2.423508,-2.423488,-2.423482
350,AT1G04171,-2.423513,-2.423510,-2.423545,-2.423546,-2.423602,-2.423566,-2.423611,-2.423680,-2.423545,...,-2.423674,-2.423640,-2.423708,-2.423662,-2.423634,-2.423678,-2.423656,-2.423686,-2.423655,-2.423646
453,AT1G05085,-2.372956,-2.372950,-2.373011,-2.373012,-2.373109,-2.373048,-2.373125,-2.373244,-2.373011,...,-2.373234,-2.373175,-2.373292,-2.373213,-2.373164,-2.373242,-2.373204,-2.373254,-2.373201,-2.373186
507,AT1G05580,-2.423549,-2.423545,-2.423592,-2.423593,-2.423669,-2.423621,-2.423681,-2.423775,-2.422920,...,-2.423767,-2.423721,-2.423812,-2.423750,-2.423712,-2.423772,-2.423743,-2.423782,-2.423741,-2.423729
511,AT1G05615,-2.369866,-2.372910,-2.373018,-2.373019,-2.373192,-2.373083,-2.373220,-2.373432,-2.373018,...,-2.373413,-2.373309,-2.373517,-2.373376,-2.373289,-2.373427,-2.373360,-2.373449,-2.373354,-2.373328
515,AT1G05650,-2.372955,-2.372948,-2.373019,-2.373020,-2.373134,-2.373062,-2.373152,-2.373291,-2.373019,...,-2.373279,-2.373210,-2.373347,-2.373254,-2.373198,-2.373288,-2.373244,-2.373303,-2.373240,-2.373223
571,AT1G06135,-2.423499,-2.423496,-2.423529,-2.423529,-2.423581,-2.423548,-2.423589,-2.423653,-2.423529,...,-2.423648,-2.423157,-2.423679,-2.423636,-2.423610,-2.423652,-2.423631,-2.423658,-2.423630,-2.423622
595,AT1G06330,-2.423487,-2.423484,-2.423515,-2.423515,-2.423564,-2.423533,-2.423572,-2.423632,-2.423515,...,-2.423627,-2.423597,-2.423656,-2.423616,-2.423592,-2.423631,-2.423612,-2.423637,-2.423610,-2.423603
675,AT1G07100,-2.423499,-2.423496,-2.423528,-2.423529,-2.423581,-2.423548,-2.423589,-2.423653,-2.423528,...,-2.423647,-2.423616,-2.423678,-2.423636,-2.423610,-2.423651,-2.423631,-2.423658,-2.423630,-2.423621
688,AT1G07190,-2.372917,-2.369815,-2.373017,-2.373018,-2.373194,-2.373083,-2.373222,-2.373436,-2.373017,...,-2.373418,-2.373312,-2.373523,-2.373380,-2.373292,-2.373432,-2.373363,-2.373454,-2.373358,-2.373331

In [62]:
duplicate_nonzero_genes.shape

(1241, 58)

In [63]:
duplicate_nonzero_genes["gene_id"].head(20).tolist()

['AT1G01410',
 'AT1G01471',
 'AT1G01870',
 'AT1G02210',
 'AT1G02391',
 'AT1G02480',
 'AT1G02590',
 'AT1G02760',
 'AT1G03515',
 'AT1G03570',
 'AT1G03720',
 'AT1G04171',
 'AT1G05085',
 'AT1G05580',
 'AT1G05615',
 'AT1G05650',
 'AT1G06135',
 'AT1G06330',
 'AT1G07100',
 'AT1G07190']

In [64]:
duplicate_groups = (
    duplicate_nonzero_genes
    .groupby(list(expression_values.columns), sort=False)
    .agg(
        n_genes=("gene_id", "size"),
        genes=("gene_id", list)
    )
    .reset_index()
)

In [65]:
duplicate_groups.shape

(172, 59)

In [66]:
duplicate_groups["n_genes"].value_counts().sort_index()

n_genes
2     64
3     13
4     11
5      7
6      8
7      2
8      8
9      6
10     5
11     7
12     2
13     6
14     3
15     5
16     7
17     2
18     6
19     2
20     1
21     2
22     2
23     2
25     1
Name: count, dtype: int64

In [67]:
duplicate_groups[
    ["n_genes", "genes"]
].sort_values(
    "n_genes",
    ascending=False
).head(10)

    n_genes                                              genes
53       25  [AT1G21860, AT1G34050, AT1G35860, AT1G53930, A...
30       23  [AT1G11620, AT1G11980, AT1G23037, AT1G44980, A...
35       23  [AT1G13605, AT1G44030, AT1G45100, AT1G53366, A...
22       22  [AT1G08670, AT1G13590, AT1G18790, AT1G19930, A...
13       22  [AT1G05580, AT1G20132, AT1G31875, AT1G46408, A...
23       21  [AT1G09030, AT1G23270, AT1G34170, AT1G48720, A...
47       21  [AT1G20375, AT1G22090, AT1G31630, AT1G33920, A...
0        20  [AT1G01410, AT1G22010, AT1G24793, AT1G24880, A...
85       19  [AT1G35500, AT1G65340, AT1G68970, AT1G75570, A...
73       19  [AT1G31090, AT1G52170, AT1G71320, AT1G77560, A...

In [68]:
sample_cols = list(expression_values.columns)

duplicate_groups["mean_expression"] = (
    duplicate_groups[sample_cols].mean(axis=1)
)

duplicate_groups["max_expression"] = (
    duplicate_groups[sample_cols].max(axis=1)
)

In [69]:
duplicate_groups[
    ["n_genes", "mean_expression", "max_expression"]
].describe()

          n_genes  mean_expression  max_expression
count  172.000000       172.000000      172.000000
mean     7.215116        -2.360995       -2.356387
std      6.158264         0.087791        0.092453
min      2.000000        -2.423718       -2.422290
25%      2.000000        -2.423530       -2.421707
50%      4.000000        -2.373093       -2.369983
75%     11.000000        -2.373059       -2.368086
max     25.000000        -1.664898       -1.636221

In [70]:
duplicate_groups[
    ["n_genes", "mean_expression", "max_expression"]
].sort_values(
    "mean_expression"
).head(20)

     n_genes  mean_expression  max_expression
53        25        -2.423718       -2.420067
36        10        -2.423683       -2.420820
5         13        -2.423681       -2.420852
47        21        -2.423681       -2.420855
23        21        -2.423666       -2.421086
30        23        -2.423664       -2.421105
77        15        -2.423662       -2.421142
13        22        -2.423659       -2.421174
85        19        -2.423659       -2.421175
101        8        -2.423659       -2.421177
3         10        -2.423643       -2.421360
34        12        -2.423612       -2.421634
65        10        -2.423604       -2.421696
40        13        -2.423597       -2.421742
11        18        -2.423594       -2.421757
59        16        -2.423590       -2.421785
124       11        -2.423583       -2.421826
33        11        -2.423581       -2.421839
108       14        -2.423579       -2.421848
114       13        -2.423576       -2.421865

In [71]:
expression_values.stack().describe()

count    1.640175e+06
mean     5.059044e+00
std      4.482899e+00
min     -2.423996e+00
25%      0.000000e+00
50%      6.345203e+00
75%      8.707930e+00
max      2.700976e+01
dtype: float64

In [72]:
expression_values.quantile([
    0,
    0.01,
    0.05,
    0.25,
    0.50,
    0.75,
    0.95,
    0.99,
    1
]).mean(axis=1)

0.00    -2.423775
0.01    -2.423589
0.05    -2.322693
0.25     0.000000
0.50     6.355284
0.75     8.717286
0.95    10.959389
0.99    12.720094
1.00    18.574495
dtype: float64

In [73]:
(expression_values == 0).sum().sum()

np.int64(151449)